extract-args: Fix a diagnostic error message that was writing to standard out--have it write to standard error instead. git-create, extract-args: Correct format for error messages--prefix each with the command name, followed by a colon, followed by a space.

diff --git a/extract-args b/extract-args
--- a/extract-args
+++ b/extract-args
@@ -3,7 +3,7 @@
 script="$(readlink -e -- "${BASH_SOURCE[0]}"; printf -- '%s' '_')"
 script="${script%
 _}"
-bash -n -- "${script}" || { printf -- '%s\n' 'extract-args: SYNTAX ERROR'; return 4; }
+bash -n -- "${script}" || { printf -- '%s\n' 'extract-args: SYNTAX ERROR' 1>&2; return 4; }
 unset script
 
 BASH_OPT_SET_START="$(shopt -op)"
@@ -303,17 +303,16 @@ function invalid-input {
 		-1 ) echo 'Wrong number of params.';;
 		* );;
 	esac
-	printf -- '%s' 'INVALID INPUT: ' 1>&2; caller 1>&2
+	printf -- '%s' 'extract-args: INVALID INPUT: ' 1>&2; caller 1>&2
 	unset options params
 	unset -n options params
 	return 1
 }
 
 function opt-fail {
-	echo "ERROR: Improperly formatted option string, variable name, or range" 1>&2
+	echo "extract-args: ERROR: Improperly formatted option string, variable name, or range" 1>&2
 	echo "specification. Use '--help' for help." 1>&2
 	caller 1>&2
-	printf '<%s>\n' "${optstr_regex}"
 	unset options params
 	unset -n options params
 	return 2
@@ -328,10 +327,10 @@ function fail {
 
 function internal-fail {
 	cat <<- 'EOF' 1>&2
-		ERROR: Internal failure in extract-args!
-
+		extract-args: ERROR: Internal failure!
 		If you are reading this, then the option parser 'extract-args' isn't working
 		properly. You'll have to fix it. Good luck!
+
 	EOF
 	caller 1>&2
 	unset options params
diff --git a/git-create b/git-create
--- a/git-create
+++ b/git-create
@@ -10,7 +10,7 @@ declare -r ARGS_FAIL="${ARGS_FAIL-0}"
 set -- "${PARAMS[@]}"
 
 function internal-fail {
-	echo 'ERROR: Internal error in '"'"'git-create'"'"'!' 1>&2
+	echo 'git-create: Internal error in '"'"'git-create'"'"'!' 1>&2
 	caller 1>&2
 	exit 5
 }
@@ -34,20 +34,21 @@ function args-fail {
 }
 
 function auth-fail {
-	echo -n 'ERROR: That username/password pair was not recognized;' 1>&2
-	echo ' repository not created.' 1>&2
+	echo 'git-create: ERROR: That username/password pair was not recognized; repository' 1>&2
+	echo 'not created.' 1>&2
 	exit 2
 }
 
 function internet-fail {
-	echo 'ERROR: Connection problems; curl exited with error code '"$1"'.' 1>&2
+	echo 'git-create: ERROR: Connection problems; curl exited with error code '"$1"'.' 1>&2
 	exit 3
 }
 
 function in-fail {
-	echo -n 'ERROR: git-create: Either could not find username or could not find repository' 1>&2
-	echo  'name; both the options and the local environment were searched.' 1>&2
+	echo 'git-create: ERROR: Either could not find username or could not find repository' 1>&2
+	echo 'name; both the options and the local environment were searched to no avail.'    1>&2
 	caller 1>&2
+	exit 4
 }
 
 function curl-fail {
